name:                polysemy-methodology
version:             0.1.5.0
license:             MIT
git:                 https://gitlab.com/homotopic-tech/polysemy-methodology
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Domain modelling algebra for polysemy
category:            Polysemy

dependencies:
- base >= 4.7 && < 5
- co-log-polysemy
- polysemy
- polysemy-plugin
- polysemy-zoo

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
